### ISSUE TITLE
I need access to maven repo of eider.

### ISSUE THREAD

**Issue by milindkpatil** [eleventy7/eider#42]
I am getting following error, can you help me to get the access.

Execution failed for task ':eider-spec:compileJava'.
> Could not resolve all files for configuration ':eider-spec:compileClasspath'.
   > Could not resolve io.eider:eider-processor:0.35-SNAPSHOT.
     Required by:
         project :eider-spec
      > Could not resolve io.eider:eider-processor:0.35-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.pkg.github.com/eleventy7/eider/io/eider/eider-processor/0.35-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://maven.pkg.github.com/eleventy7/eider/io/eider/eider-processor/0.35-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://maven.pkg.github.com/eleventy7/eider/io/eider/eider-processor/0.35-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

**Comment by eleventy7** [comment]
You will need to use this process: https://docs.github.com/en/packages/guides/configuring-gradle-for-use-with-github-packages#authenticating-to-github-packages

If you're looking at this from Aeron Cookbook, you will need to create a file eider.properties to gain access. Add the following:

gpr.usr=your-username gpr.key=personal-access-token-with-repository-read

**Comment by eleventy7** [comment]
To simplify compilation of the Aeron Cookbook code, it has been updated to remove the Eider compile time requirement. Required Eider objects are checked into the project. I'm going to close this issue now.

**Comment by milindkpatil** [comment]
Thank you very much, code is getting compiled now.
